/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ViewBingo;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.bean.GraficoNivel;
import modelos.dao.TotalProbabilidadesTextoDAO;

/**
 *
 * @author Pituba
 */
public class frmSalvarTrezeeQuatorzePontos extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmSalvarquatorzeequinzepontos
     */
    TotalProbabilidadesTextoDAO totalprobabilidadestexto = new TotalProbabilidadesTextoDAO();
    File file = new File("C:\\Meusbd\\Lotofacil.txt");
    File thirteenpointsfile = new File("C:\\Meusbd\\Trezepontos.txt");
    File fourteenpointsfile = new File("C:\\Meusbd\\Quatorzepontos.txt");
    File fifteenpointsfile = new File("C:\\Meusbd\\Quinzepontos.txt");
    File dotingraficlevelfile = new File("C:\\Meusbd\\Pontosnografico.txt");
    public frmSalvarTrezeeQuatorzePontos() {
        initComponents();
        
        Dimension dimensao = Toolkit.getDefaultToolkit().getScreenSize();
        this.setBounds(((dimensao.width)-711)/2,
                               ((dimensao.height)-480)/2,
                               711,
                               311);
        this.setMaximizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSair = new javax.swing.JButton();
        btnSelecionarTrezeeQuatorze = new javax.swing.JButton();
        pgbProcessando = new javax.swing.JProgressBar();
        lblProcessando = new javax.swing.JLabel();
        lblPercentual = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtCombinacao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnGrafico = new javax.swing.JButton();

        setTitle("Selecionador de Treze  e Quatorze Pontos Loto Fácil");
        setToolTipText("");
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ark2.png"))); // NOI18N

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnSelecionarTrezeeQuatorze.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ark2.png"))); // NOI18N
        btnSelecionarTrezeeQuatorze.setText("Selecionar quatorze e quinze pontos");
        btnSelecionarTrezeeQuatorze.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarTrezeeQuatorzeActionPerformed(evt);
            }
        });

        lblProcessando.setText("Processando ...");

        lblPercentual.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPercentual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPercentual.setText("%");

        btnCancelar.setText("Cancelar");
        btnCancelar.setMaximumSize(new java.awt.Dimension(235, 33));
        btnCancelar.setMinimumSize(new java.awt.Dimension(235, 33));
        btnCancelar.setPreferredSize(new java.awt.Dimension(235, 33));
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtCombinacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setText("Sorteio: ");

        btnGrafico.setText("Gráfico");
        btnGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addGap(31, 31, 31))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pgbProcessando, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSelecionarTrezeeQuatorze, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtCombinacao, javax.swing.GroupLayout.PREFERRED_SIZE, 516, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProcessando, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(lblPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGrafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(txtCombinacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGrafico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addComponent(lblProcessando)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgbProcessando, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPercentual, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(btnSelecionarTrezeeQuatorze, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addComponent(btnSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnSelecionarTrezeeQuatorzeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarTrezeeQuatorzeActionPerformed
        
        totalprobabilidadestexto.setCondicaoInicialZerada(false);
        if(!txtCombinacao.equals("")){
            if(!thirteenpointsfile.exists() || !fourteenpointsfile.exists()){
                totalprobabilidadestexto.setCondicaoInicialZerada(true);
                try {
                    fifteenpointsfile.createNewFile();
                    try {
                         thirteenpointsfile.createNewFile();
                        try{
                            fourteenpointsfile.createNewFile();
                        }catch(IOException e)
                             {
                                 JOptionPane.showMessageDialog(null, "Erro: " + e + " ao tentar criar o arquivo de quatorze pontos!",
                                                        "Criando o arquivo de quatorze pontos", JOptionPane.ERROR_MESSAGE);  
                             }                
                    } catch (IOException ex) 
                          {
                              JOptionPane.showMessageDialog(null, "Erro: " + ex + " ao tentar criar o arquivo de treze pontos!",
                                                 "Criando o arquivo de treze pontos", JOptionPane.ERROR_MESSAGE);
                          } 
                } catch (IOException ex)
                      {
                          JOptionPane.showMessageDialog(null, "Erro: " + ex + " ao tentar criar o arquivo de quinze pontos!",
                                                 "Criando o arquivo de quinze pontos", JOptionPane.ERROR_MESSAGE);
                      }
            }        
                totalprobabilidadestexto.selecionaresalvartrezeequatorzepontos(file, thirteenpointsfile, 
                                                                   fourteenpointsfile,fifteenpointsfile, txtCombinacao.getText().trim());   
                
                
        if(!dotingraficlevelfile.exists()){
                    try {
                         dotingraficlevelfile.createNewFile();             
                    } catch (IOException ex) 
                          {
                              JOptionPane.showMessageDialog(null, "Erro: " + ex + " ao tentar criar o arquivo de pontos do gráfico!",
                                                 "Criando o arquivo pontos do gráfico", JOptionPane.ERROR_MESSAGE);
                          }           
            }        
       
        totalprobabilidadestexto.retornaIndex(file, dotingraficlevelfile, txtCombinacao.getText().trim());
        }else{
            JOptionPane.showMessageDialog(null, "Por favor, digite uma combinação com quinze dezenas",
                    "Digite a combinação correta!", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnSelecionarTrezeeQuatorzeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //totalprobabilidadestexto.salvartrezepontos(fileteste, "01 02 03 04 05 06 07 08 09 10 11 13 14 15 17");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoActionPerformed
        GraficoNivel graficonivel = new GraficoNivel();
        graficonivel.GraficoNivel(dotingraficlevelfile);        
    }//GEN-LAST:event_btnGraficoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGrafico;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSelecionarTrezeeQuatorze;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel lblPercentual;
    public static javax.swing.JLabel lblProcessando;
    public static javax.swing.JProgressBar pgbProcessando;
    private javax.swing.JTextField txtCombinacao;
    // End of variables declaration//GEN-END:variables
}
